apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: keycloakns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: keycloakns
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
