name: Deploy (Roll out) Full Infra and App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo az aks install-cli
          pip install ansible[azure] kubernetes

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Provision Azure Infrastructure (infra.yml)
        run: ansible-playbook -i ansible/inventory.ini ansible/infra.yml

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group keycloak-aks-rg --name keycloak-aks --overwrite-existing
          cat ~/.kube/config | base64 > kubeconfig.b64

      - name: Deploy App (deploy.yml)
        env:
          KUBECONFIG: ${{ github.workspace }}/.kube/config
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/deploy.yml
