name: Destroy (Disassemble) Full Infra and App

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo az aks install-cli
          pip install ansible[azure] kubernetes

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: 

      - name: Destroy Everything (destroy.yml)
        run: ansible-playbook -i ansible/inventory.ini ansible/destroy.yml
